theme = 'PaperMod'

title = "Filipe Almeida"
author = "Filipe Almeida"
copyright = "Copyright © 2020, Filipe Almeida"

languageCode = "en-GB"

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

enableRobotsTXT = true
enableEmoji = true
canonifyURLs = true

[permalinks]
blog = "/:slug/"
tags = "/blog/:slug"

[params]
# See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
title = "Filipe Almeida"
description = "Personal website and blog where I share my thoughts"

# The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
# Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.
favicon = "images/favicon.png"

# See https://gohugo.io/templates/internal#twitter-cards and
# https://gohugo.io/templates/internal#open-graph.
images = ["images/share.png"]

# This theme will, by default, inject a made-with-line at the bottom of the page.
hideMadeWithLine = true

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = true
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.css]
      decimals = -1
      keepCSS2 = false
    [minify.tdewolff.html]
      keepConditionalComments = false
      keepDefaultAttrVals = false
      keepDocumentTags = false
      keepEndTags = false
      keepQuotes = false
      keepWhitespace = false
    [minify.tdewolff.js]
    [minify.tdewolff.json]
    [minify.tdewolff.svg]
      decimals = -1
    [minify.tdewolff.xml]
      keepWhitespace = false
